// Generated by CoffeeScript 1.3.1

  (function() {
    var ObjectId, Schema, User, UserModel, connection, makeNewUser, mongoose, routes, user;
    routes = void 0;
    mongoose = require("mongoose");
    connection = mongoose.createConnection("mongodb://localhost/newpla2");
    Schema = mongoose.Schema;
    ObjectId = Schema.ObjectId;
    User = new Schema({
      login: String,
      password: String
    });
    UserModel = connection.model("users", User);
    user = new UserModel();
    UserModel.findOne({
      login: "ryan"
    }, function(err, doc) {
      return console.log(doc);
    });
    makeNewUser = function(login, pass) {
      user.login = login;
      return user.password = pass;
    };
    makeNewUser("dude", "dude$1234");
    routes = function(app) {
      app.get('/login', function(req, res) {
        return res.render("" + __dirname + "/views/login", {
          title: 'Login',
          stylesheet: 'login'
        });
      });
      app.post('/sessions', function(req, res) {
        return UserModel.findOne({
          login: req.body.user
        }, function(err, doc) {
          if (err) {
            req.flash("error", "The username " + req.body.user + " is incorrect.");
            return res.redirect('/login');
          } else {
            if (doc.password === req.body.password) {
              req.session.currentUser = req.body.user;
              req.flash('info', "You are now logged in as " + req.session.currentUser + ".");
              res.redirect('/dash/class');
            } else {
              req.flash('error', 'The password was incorrect. Please login again.');
              return res.redirect('/login');
            }
          }
        });
      });
      return app.del('/sessions', function(req, res) {
        return req.session.regenerate(function(err) {
          req.flash('info', 'you have been logged out.');
          return res.redirect('/login');
        });
      });
    };
    return module.exports = routes;
  }).call(this);

