// Generated by CoffeeScript 1.3.1
(function() {
  var Pie, routes;

  Pie = require('../../models/pie');

  routes = function(app) {
    return app.get('/', function(req, res) {
      return Pie.active(function(err, pies) {
        return res.render("" + __dirname + "/views/index", {
          title: "What's Warm",
          stylesheet: 'sidewalk',
          pies: pies
        });
      });
    });
  };

  module.exports = routes;

}).call(this);
