// Generated by CoffeeScript 1.3.1
(function() {
  var Pie, PieFactory, app, assert, express, request;

  require('../_helper');

  express = require('express');

  assert = require('assert');

  request = require('request');

  app = require("../../server");

  PieFactory = require('../pie-factory');

  Pie = require('../../models/pie');

  describe('sidewalk', function() {
    return describe('GET /', function() {
      var body;
      body = null;
      before(function(done) {
        var minutesAgo;
        minutesAgo = function(num) {
          return (new Date).getTime() - (1000 * 60 * num);
        };
        return PieFactory.createSeveral(function() {
          return Pie.getById('Key-Lime', function(err, pie) {
            pie.state = 'making';
            pie.stateUpdatedAt = minutesAgo(2);
            return pie.save(function() {
              return Pie.getById('Chicken', function(err, pie) {
                return pie.making(function() {
                  return Pie.getById('Apple', function(err, pie) {
                    pie.state = 'ready';
                    pie.stateUpdatedAt = minutesAgo(2);
                    return pie.save(function() {
                      return Pie.getById('Cherry', function(err, pie) {
                        return pie.ready(function() {
                          return Pie.active(function(err, _pies) {
                            var pies;
                            pies = _pies;
                            return request({
                              uri: "http://localhost:" + app.settings.port + "/"
                            }, function(err, response, _body) {
                              body = _body;
                              return done();
                            });
                          });
                        });
                      });
                    });
                  });
                });
              });
            });
          });
        });
      });
      it("has title", function() {
        return assert.hasTag(body, '//title', "Hot Pie - What's Warm");
      });
      it("Key Lime is 'almost-ready'", function() {
        return assert.hasTagMatch(body, '//li[@class="almost-ready sweet"]', /Key Lime/);
      });
      it("Chicken is 'not-ready'", function() {
        return assert.hasTagMatch(body, '//li[@class="not-ready savory"]', /Chicken/);
      });
      it("Apple is 'warm'", function() {
        return assert.hasTagMatch(body, '//li[@class="warm sweet"]', /Apple/);
      });
      return it("Cherry is 'pipin-hot'", function() {
        return assert.hasTagMatch(body, '//li[@class="pipin-hot sweet"]', /Cherry/);
      });
    });
  });

}).call(this);
