// Generated by CoffeeScript 1.3.1
(function() {

  module.exports = function(app) {
    var socketIO;
    socketIO = require('socket.io').listen(app);
    if (!app.settings.socketIO) {
      app.set('socketIO', socketIO);
    }
    return socketIO.sockets.on('connection', function(socket) {
      return console.log("CONNECTED");
    });
  };

}).call(this);
