// Generated by CoffeeScript 1.3.1
(function() {
  var Pie, PieFactory,
    __slice = [].slice;

  Pie = require('../models/pie');

  PieFactory = {
    createSeveral: function(callback) {
      var applePie, cherryPie, chickenPie, createOne, keyLimePie, pieAttributes, runSequentially;
      keyLimePie = {
        name: 'Key Lime',
        type: 'sweet'
      };
      chickenPie = {
        name: 'Chicken',
        type: 'savory',
        state: 'making'
      };
      applePie = {
        name: 'Apple',
        type: 'sweet'
      };
      cherryPie = {
        name: 'Cherry',
        type: 'sweet',
        state: 'ready',
        stateUpdatedAt: (function() {
          return (new Date).getTime() + (1000 * 60 * 60 * 24 * 365 * 1000);
        })()
      };
      pieAttributes = [keyLimePie, chickenPie, applePie, cherryPie];
      createOne = this.createOne;
      runSequentially = function() {
        var item, otherItems;
        item = arguments[0], otherItems = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
        return createOne(item, function() {
          if (otherItems.length) {
            return runSequentially.apply(null, otherItems);
          } else {
            return callback();
          }
        });
      };
      return runSequentially.apply(null, pieAttributes);
    },
    createOne: function(attributes, callback) {
      var pie;
      pie = new Pie(attributes);
      return pie.save(function(err, pie) {
        return callback(err, pie);
      });
    }
  };

  module.exports = PieFactory;

}).call(this);
