// Generated by CoffeeScript 1.3.1
(function() {
  var Pie, routes;
  var mongoose = require('mongoose'); // include mongoose package
  var connection = mongoose.createConnection('mongodb://localhost/newpla2');    //creates the mongo connection   

  //initializzes an empty schema object
  var Schema = mongoose.Schema
  , ObjectId = Schema.ObjectId;
  
  //populates the schema object with properties  
  
  var Problem = new Schema({
  title : String,
  body: String
  });

  var Assignment = new Schema({
     instructions: String,
     problem: [Problem]
  });

  var AssignmentModel = connection.model('Assignment', Assignment); 
  
  

  routes = function(app) {
    app.get('/create', function(req, res) {
      return res.render("" + __dirname + "/views/class/create.jade", {
        title: "Create Problem",
        stylesheet: 'create'
      });
    });
    
    app.post('/',function(req,res) {
      var assignment = new AssignmentModel(); //this creates a new empty assignment model
      assignment.instructions = 'Here are the instructions for the problem by Bieber4';
      assignment.problem.push({title: req.body.problemtitle, body:req.body.problem});
      //this saves the new assignment
      assignment.save();
      
    });
    
    return app.namespace('/dash', function() {
      app.all('/*', function(req, res, next) {
        if (!req.session.currentUser) {
          req.flash('error', 'Please login.');
          res.redirect('/login');
          return;
        }
        return next();
      });
      return app.namespace('/class', function() {
        app.get('/', function(req, res) {
          var assignment;
          assignment= new AssignmentModel();
          return res.render("" + __dirname + "/views/class/dash.jade", {
            title: "Dashboard",
            stylesheet: 'admin',
            });
          });
        });
      
        return app.post('/', function(req, res) {
           
          return;
          var attributes;
          attributes = {
            problemtitle: req.body.problemtitle,
            problem: req.body.problem,
          };
          
        });
      });
    };
  module.exports = routes;
}).call(this);

